name: G10_Currencies_3.13
channels:
  - defaults
dependencies:
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - contourpy=1.3.1
  - cycler=0.11.0
  - expat=2.6.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - icu=73.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libpng=1.6.39
  - libpq=17.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numpy=2.1.3
  - numpy-base=2.1.3
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pillow=11.0.0
  - ply=3.11
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.13.0
  - python-dateutil=2.9.0post0
  - python_abi=3.13
  - qt-main=5.15.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - tornado=6.4.1
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - click==8.1.7
      - colorama==0.4.6
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - pandas==2.2.3
      - pip==24.3.1
      - pygments==2.18.0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - rich==13.9.4
      - setuptools==75.6.0
      - shellingham==1.5.4
      - tqdm==4.67.1
      - typer==0.14.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wheel==0.45.1
      - win32-setctime==1.1.0
