name: G10_Currencies
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - expat=2.6.3
  - libffi=3.4.4
  - libmpdec=4.0.0
  - openssl=3.0.15
  - python=3.13.0
  - python_abi=3.13
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.40
  - vs2015_runtime=14.40.33807
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - click==8.1.7
      - colorama==0.4.6
      - loguru==0.7.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - numpy==2.1.3
      - pandas==2.2.3
      - pip==24.3.1
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - rich==13.9.4
      - setuptools==75.6.0
      - shellingham==1.5.4
      - six==1.16.0
      - tqdm==4.67.1
      - typer==0.14.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - wheel==0.45.1
      - win32-setctime==1.1.0
